name: CI pipelines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpstan-checks:
    name: phpstan-checks
    runs-on: ubuntu-latest

    steps:
      - name: Fetch PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute PHPSTAN checks
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 128M

  phpcs-checks:
    name: phpcs-checks
    runs-on: ubuntu-latest

    steps:
      - name: Fetch PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute PHPCS checks
        run: ./vendor/bin/phpcs --standard=PSR12 app
